# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message="Номер должен быть следующего формата: '+99999999'. Не больше 15 цифр", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
