# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон'),
        ),
    ]
